print('Your name?')
name = input()
print('Your height?')
height = input()
print('Your weight?')
weight = input()

print('Hi ',name,'.')
print('Your height is ',height,' and weight is ',weight,'.')
print('You are MF fat!')